# eqnlint/__init__.py
__all__ = ["__version__"]

try:
    # Preferred: version file generated by setuptools-scm during build
    from ._version import version as __version__
except Exception:
    # Fallback: ask the installed metadata (works after pip install)
    try:
        from importlib.metadata import version as _pkg_version  # Py3.8+
        __version__ = _pkg_version("eqnlint")
    except Exception:
        # Last resort (e.g., bare source tree without tags)
        __version__ = "0.0.0"
